spring:
  profiles:
    active: dev
---
server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true    
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: reinput-auth-service
  datasource:
    url: jdbc:h2:mem:reinput;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/auth/oauth2/kakao/callback/v1"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  secret: ${JWT_SECRET}
  accessToken:
    expiration: 3600
  refreshToken:
    expiration: 86400
logging:
  level:
    org.springframework.web: DEBUG
    security: DEBUG